plugins:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
  eslint:
    enabled: true
    config:
      extensions:
        - .js
exclude_patterns:
  - ci/
  - vendor/
  - node_modules/
  - bower_components/
  - application/tests/
  - application/third_party/
