image: docker:17.06
variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    MOUNT_POINT: $CI_PROJECT_DIR/test

stages:
    - test

test-codereview:
    stage: test
    environment: testing
    script:
        - docker run --rm --tty --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc --env CODECLIMATE_CODE="$PWD" --env CONTAINER_TIMEOUT_SECONDS=3600 codeclimate/codeclimate:0.78.1 analyze -e phpmd -e eslint -f html > codereview.html && cat codereview.html | grep -i 'no issue'
    artifacts:
        when: always
        paths: [codereview.html]
    only:
        - testing

test-unitary:
    services:
        - rabbitmq:3.6-management
        - docker:dind
    stage: test
    environment: testing
    before_script:
        -
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - mkdir -v test
        - touch test.txt
        - echo $CI_PROJECT_DIR
        - echo $MOUNT_POINT
        - docker run --rm --tty -v "$MOUNT_POINT:/app" debian:latest ls -l /app
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
