image: docker:17.06

stages:
    - test

test-codereview:
    stage: test
    environment: testing
    script:
        - docker run --rm --tty --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc --env CODECLIMATE_CODE="$PWD" --env CONTAINER_TIMEOUT_SECONDS=3600 codeclimate/codeclimate:0.78.1 analyze -e phpmd -e eslint -f html > codereview.html && cat codereview.html | grep -i 'no issue'
    artifacts:
        when: always
        paths: [codereview.html]
    only:
        - testing

test-unitary:
    services:
        - rabbitmq:3.6-management
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - cp -pv composer.json tests
        - docker run --rm --tty --volume $PWD:/app --workdir /app/tests composer:1.4 install --ignore-platform-reqs --no-scripts --no-progress
        - cp -rpv tests/vendor/codeigniter/framework/* tests
        - sed -i 's~$config\[\x27composer_autoload\x27\] = FALSE;~$config["composer_autoload"] = FCPATH."vendor/autoload.php";~' tests/application/config/config.php
        - mkdir -p tests/vendor/santiane/rabbitmq_client
        - cp -rpv libraries tests/vendor/santiane/rabbitmq_client
        - cp -rpv config tests/vendor/santiane/rabbitmq_client
        - cp -rpv helpers tests/vendor/santiane/rabbitmq_client
        - cp -rpv ci tests
        - docker run --rm --tty -e CI_ENV=testing --volume $PWD:/app --workdir /app/tests --entrypoint="ci/docker_entrypoint_php.sh" php:7.1 php index.php unity runComplete
    artifacts:
        when: always
        paths: [tests/result_test.html]
    only:
        - testing
