image: docker:17.06

services:
    - docker:dind

stages:
    - test

test-unitary:
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - docker ps -a
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
