image: docker:17.06

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    MOUNT_POINT: $CI_PROJECT_DIR/test

stages:
    - test

test-unitary:
    services:
        - rabbitmq:3.6-management
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - mkdir -v test
        - touch test/test.txt
        - docker run --rm --tty -v $MOUNT_POINT:/app debian:latest ls -l /app
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
