image: docker:17.06

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

stages:
    - test

test-unitary:
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - ls -l
        - docker run -v ${CI_PROJECT_DIR}:/mnt ubuntu ls /mnt
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
