image: docker:17.06

services:
    - name: docker:dind
      entrypoint: ["ci/dind.entrypoint.sh"]

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
stages:
    - test

test-unitary:
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - docker version
        - docker pull httpd:2.4
        - docker pull httpd:2.4
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
