image: docker:17.06

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    SHARED_PATH: /builds/shared/$CI_PROJECT_PATH

stages:
    - test

test-unitary:
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - mkdir -p ${SHARED_PATH}
        - touch ${SHARED_PATH}/test_file
        - echo $SHARED_PATH
        - docker run -v ${SHARED_PATH}:/mnt ubuntu ls /mnt
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
