image: docker:17.06

services:
    - docker:dind

variables:
    SHARED_PATH: /builds/shared/$CI_PROJECT_PATH

stages:
    - test

test-unitary:
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - docker run --rm -v /builds/shared/$CI_PROJECT_PATH:/builds/shared/$CI_PROJECT_PATH ubuntu ls -l /builds/shared/$CI_PROJECT_PATH
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
