image: docker:17.06

stages:
    - test

test-unitary:
    services:
        - rabbitmq:3.6-management
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - ls -l
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
