image: docker:17.06

stages:
    - test

test-unitary:
    stage: test
    environment: testing
    before_script:
        - find . -type d -exec chmod 755 {} +
        - find . -type f -exec chmod 644 {} +
        - find ./ci -type f -exec chmod 755 {} +
    script:
        - pwd
        - ls -l
        - ls -l /
        - docker run --rm -v ${CI_PROJECT_DIR}:/app ubuntu ls -l /app
    artifacts:
        when: always
        paths: [test/result_test.html]
    only:
        - testing
